/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tournamentclass;

import javax.swing.JOptionPane;

/**
 *
 * @author Matthias
 */
public class TournamentClassGUI extends javax.swing.JFrame {

    private TournamentClassListModel model = new TournamentClassListModel();
    
    /**
     * Creates new form TournamentClassGUI
     */
    public TournamentClassGUI() {
        initComponents();
        
        liClasses.setModel(model);
        
        this.updateCounts();
    }
    
    public void updateCounts(){
        tfClassCount.setText(model.getSize()+"");
        tfUnusedClassCount.setText(model.getSize()+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        liClasses = new javax.swing.JList<>();
        panelSouth = new javax.swing.JPanel();
        lbClassCount = new javax.swing.JLabel();
        tfClassCount = new javax.swing.JTextField();
        lbSpacer = new javax.swing.JLabel();
        lbUnusedClassCount = new javax.swing.JLabel();
        tfUnusedClassCount = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miAdd = new javax.swing.JMenuItem();
        miRemove = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCenter.setLayout(new java.awt.GridLayout(1, 1));

        liClasses.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(liClasses);

        panelCenter.add(jScrollPane1);

        getContentPane().add(panelCenter, java.awt.BorderLayout.CENTER);

        panelSouth.setLayout(new java.awt.GridLayout(1, 5));

        lbClassCount.setText("Classes:");
        panelSouth.add(lbClassCount);

        tfClassCount.setEditable(false);
        panelSouth.add(tfClassCount);
        panelSouth.add(lbSpacer);

        lbUnusedClassCount.setText("Unused Classes");
        panelSouth.add(lbUnusedClassCount);

        tfUnusedClassCount.setEditable(false);
        panelSouth.add(tfUnusedClassCount);

        getContentPane().add(panelSouth, java.awt.BorderLayout.SOUTH);

        jMenu1.setText("Classes");

        miAdd.setText("Add Class");
        miAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddActionPerformed(evt);
            }
        });
        jMenu1.add(miAdd);

        miRemove.setText("Remove Class(es)");
        jMenu1.add(miRemove);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddActionPerformed
        String name = JOptionPane.showInputDialog(this, "Enter a name for the class.");
        if(name != null){
            model.add(new TournamentClass(name));
            updateCounts();
        }
    }//GEN-LAST:event_miAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TournamentClassGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TournamentClassGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TournamentClassGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TournamentClassGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TournamentClassGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbClassCount;
    private javax.swing.JLabel lbSpacer;
    private javax.swing.JLabel lbUnusedClassCount;
    private javax.swing.JList<String> liClasses;
    private javax.swing.JMenuItem miAdd;
    private javax.swing.JMenuItem miRemove;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelSouth;
    private javax.swing.JTextField tfClassCount;
    private javax.swing.JTextField tfUnusedClassCount;
    // End of variables declaration//GEN-END:variables
}
